name: Essaim Apps
author: Olli Pöyry
#markdown: redcarpet
pygments: true
baseurl: ""
##baseurl: /herring-cove
description: Software specialist
github: http://www.github.com/arnp
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: rnpatel[at]me.com
location: 42Â°2'16"N   70Â°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.

markdown: kramdown
pygments : false